name: Perform checks

on:
  push:
    branches:
      - '*'

jobs:
  check:
    name: Check
    runs-on: 'ubuntu-latest'
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: golangci-lint
        uses: golangci/golangci-lint-action@v2
